spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: csyzsj520
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false

server:
  port: 8080